<AllMatches>:
    name:"allmatches"

    MDBoxLayout:
        orientation:"vertical" 
        spacing: "12dp"
    
        MDToolbar:
            id:Toolbar
            title:"Matches"
            anchor_title:"center"
            pos_hint: {"top":1}

        ScrollView:
            MDList:
                id:matchlist
<BlackLabel@MDLabel>
    theme_text_color: "Custom"
    text_color: 0, 0, 0, 1
    font_name: "LibreBaskerville-Regular.ttf"

<MatchesItem>
    id:matchesitem
    size_hint_y:None
    height:"100dp"
    elevation:20
    adaptive_height:True
    MDCard:
        orientation: "vertical"
        border_radius: 20
        radius: [15]
        ripple_behavior: True
        on_release: root.show_matches()
        BoxLayout:
            id: box
            orientation:"vertical"
            size_hint_y:None
        
            BoxLayout:
                orientation:"vertical"
                size_hint: 1,0.22
                padding:"5dp"
    
                BlackLabel:
                    id:matchlbl
                    text:"[u]IPL 3rd match CSK vs RCB[u]"
                    markup:True
                    font_size:"12sp"
                    bold:True
                    halign:"center"
                        
            BoxLayout:
                size_hint: 1,0.75
                
                Image:
                    source:"csk.jpg"
                BoxLayout:
                    orientation:"vertical"
                    BlackLabel:
                        text:"VS"
                        font_size:"25sp"
                        halign:"center"
                    BlackLabel:
                        text:"25-4-2021"
                        bold:True
                        font_size:"12sp"
                        halign:"center"  
                Image:
                    source: "rcb.jpg"
