<AllMatches>:
    name:"allmatches"

    MDBoxLayout:
        orientation:"vertical" 
        spacing: "12dp"
    
        MDToolbar:
            id:Toolbar
            title:"Matches"
            anchor_title:"center"
            pos_hint: {"top":1}
            md_bg_color:128/255, 0, 0, 1


        ScrollView:
            MDList:
                id:matchlist
                height:"140dp"
                #on_press:root.show_matches()
                
<BrownLabel@MDLabel>
    theme_text_color: "Custom"
    text_color: 128/255, 0, 0, 1
    font_name: "LibreBaskerville-Regular.ttf"
    

<Matches>
    id: card
    orientation: "vertical"
    size_hint: .9, None
    height: self.minimum_height
    ripple_behavior: True
    border_radius: 20
    radius: [15]
    md_bg_color: 1, 245/255, 230/255, 1
    on_release: root.show_matches()
    BoxLayout:
        id: box
        orientation:"vertical"
        #pos_hint:{"center_x":0.5,"center_y":0.5}
        size_hint_y:None
       
        BoxLayout:
            orientation:"vertical"
            size_hint: 1,0.22
            pos_hint:{"center_x":0.5,"center_y":0.5}
            padding:"5dp"
            
            BrownLabel:
                id:matchlbl
                text:"[u]IPL 3rd match CSK vs RCB[u]"
                markup:True
                font_size:"12sp"
                bold:True
                halign:"center"
        
        BoxLayout:
            orientation:"vertical"
            
            BoxLayout:
                Image:
                    source:"csk.jpg"
                BoxLayout:
                    orientation:"vertical"
                    Widget:
                        size:0.05,0.05
                    BrownLabel:
                        text:"VS"
                        font_size:"25sp"
                        halign:"center"
                    BrownLabel:
                        text:"25-4-2021"
                        bold:True
                        font_size:"12sp"
                        halign:"center"  
                Image:
                    #source:"D:/Cricket/KivyMD-master/demos/Andriod/RCB.jpg"
                    source: "rcb.jpg"
                    #source:app.bimagepath
